spring:
  application:
    name: social_media

  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey123456
  expiration: 3600000  # 1 soat

services:
  s3:
    endpoint: http://localhost:9000
    minio-host: https://localhost:9000
    access-key: user
    secret-key: password
    bucket-name: user-project
    region: us-east-1

server:
  port: 8081  # Port to avoid conflict, you can change it to any available port
